### ISSUE TITLE
Streakrewards

### ISSUE THREAD

**Issue by codingvincee** [mineclaps/mineclaps#1]
### Server of origin

Survival

### Rundown

When players join, they get a reward for being on a streak. Daily rewards for example.

### How would this benefit players?

Players get rewarded for their loyalty to the server.

### How would the community react if it were added?

Ecstatic

**Comment by dylansoft** [comment]
Sounds like a great idea!

I'll wait a few days before implementing this to see what people think of your suggestion.

**Comment by codingvincee** [comment]
Currently added the plugin to the DEV server.

- [ ] Setup permissions
- [ ] Determine daily prizes
- [ ] Move to PRD

**Comment by codingvincee** [comment]
In the coming days I'll post a proposal of rewards

**Comment by dylansoft** [comment]
updates?

**Comment by codingvincee** [comment]
Idling, haven't come up with a loot table yet
