### ISSUE TITLE
Bed regen

### ISSUE THREAD

**Issue by DarkPyro124LTU** [mineclaps/mineclaps#10]
### Server of origin

When people go to sleep it will slowly regenerate their health

### How would this benefit gameplay?

I have nothing to add

**Comment by Lovelyes** [comment]
I don't really see the use of this. Since they can get food from voting which regens the health and fills the food bar

**Comment by dylansoft** [comment]
I can see a use for this, could it possibly be a skill of sorts?
Like a mending enchantment, but for your HP.
I'll have a look into this and I'll respond back in a few hours when I've thought it through
