### ISSUE TITLE
Leveled mobs

### ISSUE THREAD

**Issue by DarkPyro124LTU** [mineclaps/mineclaps#11]
### Server of origin

Survival

### Rundown

Mobs will have different kinds of levels the higher the level the stronger the mob
The lower the mob the weaker. 

### How would this benefit gameplay?

It will make the game a bit harder adding to the hard mode already set some would enjoy it some would hate it. 

### Other information

I have nothing to add

**Comment by Lovelyes** [comment]
Could be fun. But lots of setup to do. Especially since the mobs will be not based on player since we don't have mcmmo on the server which is compatible with it. So a new player will have a lvl 5 zombie with idk diamond armor and sword... Bit too OP for them

**Comment by codingvincee** [comment]
Might be quite some work, but there are most likely some templates we could use. If not, hopefully there is another grading system to scale mobs.

**Comment by dylansoft** [comment]
This sounds like a good idea, could tie in well with a mob-arena of sorts with enemies in equal difficulty proportional to the player's 'attack level' (or something like that).
