### ISSUE TITLE
Discord discussions

### ISSUE THREAD

**Issue by Lovelyes** [mineclaps/mineclaps#12]
### Server of origin

< type your answer here, without the brackets >
Discord 

### Rundown

< type your answer here, without the brackets >
Discussions on discord for faster responds. 

### What has prompted you to suggest this change?

< type your answer here, without the brackets >
I think discord is faster then github. 

### How would this benefit gameplay?

< type your answer here, without the brackets >
Faster communication faster fixing and adding. 

### Other information

< type your answer here, without the brackets >
-

**Comment by dylansoft** [comment]
Follow the template, submit a new issue.
