### ISSUE TITLE
uh i went to a pw that sells kits like god i click the picaxe and it also said GOD picaxe but i got  a GOD helmet and took 27k from me

### ISSUE THREAD

**Issue by yellowpen123** [mineclaps/mineclaps#19]
### Server of origin

< type your answer here, without the brackets >

  
### Rundown

< type your answer here, without the brackets >

  
### What is the expected outcome?

< type your answer here, without the brackets >

### What is the actual outcome?

< type your answer here, without the brackets >

### Steps to reproduce

1. < replace me >
2. < replace me >
3. < replace me >  
< add as many steps as you see fit. >

### Other information

< type your answer here, without the brackets >

**Comment by dylansoft** [comment]
Resubmit using the format.
