### ISSUE TITLE
Selective Disenchanter

### ISSUE THREAD

**Issue by DarkPyro124LTU** [mineclaps/mineclaps#2]
### Server of origin

Survival

  
### Rundown

Disenchants a certain enchant like Thorns III on a armor piece but leaves the others how they were before ex: A chestplate Has Mending Prot VI and Thorns III with the new game feature it only would remove Thorns III or The others mentioned 

### How would this benefit players?

Players would remove the enchants they don't want ex: On playtime rank or Premium rank kits

### How would the community react if it were added?

Various reactions may some be against it and some could be Supportive of it

**Comment by dylansoft** [comment]
This seems like a good idea,
I'll look into it and see what we can come up with.
