### ISSUE TITLE
Punishment additions to discord

### ISSUE THREAD

**Issue by DarkPyro124LTU** [mineclaps/mineclaps#3]
### Server of origin

Survival

  
### Rundown

Jail Punishment showment in discord

### How would this benefit players?

It wont benefit the players it will just show who was jailed or not

  
### Other information

It will show who was jailed and for how much

**Comment by dylansoft** [comment]
I believe you've written your answers inside of the brackets,
could you edit your issue and remove the brackets?

**Comment by codingvincee** [comment]
I have an idea for this, will pick it up later.
