### ISSUE TITLE
Territory/party Wars 

### ISSUE THREAD

**Issue by DarkPyro124LTU** [mineclaps/mineclaps#5]
### Server of origin

 Survival

  
### Rundown

An Event where people fight for their land. Peoples claims will stay the same but it will be in a certain party's control. This event could happen on the day or days that the server has more people and if this gets added to the server there should be a map which can be accessed by any player and it will show who owns what. 

### How would this benefit gameplay?

This addition could interest newer players to join the server, It will encourage people to PVP more and to create party's.

**Comment by codingvincee** [comment]
Some sort of battle grounds?

**Comment by DarkPyro124LTU** [comment]
Sort of. A text will pop on people's screen territory or party wars begin then they will have to conquer people's claims or just unlcaimed land. Ofc the claims will stay how they were before. Then in the next wars they can retake the territories and it can be connected to the clapsian kigdom suggestion as for if you like burn down someones house or smth you can get taxed money or smth ofc this can be discussed more in the future.
