### ISSUE TITLE
Adding looting to kits

### ISSUE THREAD

**Issue by ghost** [mineclaps/mineclaps#6]
So basically what I'd want to implement is adding looting to swords equal to fortune on the pickaxe for the kits.
Since God has fortune V swords would have looting V
Since King has fortune IV swords would have looting IV
Since Champion has fortune III swords would have looting III
And for OG kit when it's release to have looting added according to fortune

**Comment by dylansoft** [comment]
Why wasn't the template followed for this one?
These are some alright ideas, but they seem very pay-to-win.
Any ideas of how to balance this one @codingvincee ?
