### ISSUE TITLE
Smooth timber plugin

### ISSUE THREAD

**Issue by DarkPyro124LTU** [mineclaps/mineclaps#8]
### Server of origin

Survival

  
### Rundown

When you remove the bottom of log a tree the rest of the tree falls down

### How would this benefit gameplay?

Players wouldn't have to take a lot time to chop down trees. 

  
### Other information

If needed this feature could be unlocked if played for longer periods of time like 3 or more days

**Comment by dylansoft** [comment]
This seems like a great idea, but I'm not massively on-board with the playtime requirement.
Could it possibly require an enchantment instead?

**Comment by DarkPyro124LTU** [comment]
> This seems like a great idea, but I'm not massively on-board with the playtime requirement.
> Could it possibly require an enchantment instead?

I meant by if the feature is too overpowered it could be unlocked by playing a certain ammount of time or smth this but if its not really that op then anyone could have it but that too

**Comment by Lovelyes** [comment]
I would say no to this it's too Op

**Comment by dylansoft** [comment]
> I would say no to this it's too Op

Alright, so what would make it not "too op"?

**Comment by codingvincee** [comment]
Not a fan of it, but possible if the majority wants this. There is a datapack which offers this functionality, no need of a plugin which might just mess with the performance. Your tool will take the amount of duration you'd lose by chopping the tree block by block. Removes the OP part but opens a new problem: possibility of whining.

Let's have a staff vote and then a playervote.

**Comment by Lovelyes** [comment]
> > I would say no to this it's too Op
> 
> Alright, so what would make it not "too op"?

Not to happen at every tree like mcmmo having a timer on it. Like mcmmo. I like the plugin just think it's a bit too OP bec u click a tree especially with those unbreakable axes where a tree takes 1 second to chop. U can chop a whole forest in 15 seconds. And have so much wood that I will need to make the sell price lower. Which makes the shop again mostly farming for best sell prices which we don't want.

**Comment by dylansoft** [comment]
> > > I would say no to this it's too Op
> > 
> > 
> > Alright, so what would make it not "too op"?
> 
> Not to happen at every tree like mcmmo having a timer on it. [cut]

Okay, so, a cooldown?
Sound good, how about a 2-3 second cooldown?
